---
version: "2.0"

services:
  akash:
    image: chandrastation/dig
    env:
      - CHAIN_ID=dig-testnet-2
      - GENESIS_URL=https://github.com/faddat/dig/raw/master/networks/testnet-2/genesis.json
      - DIGD_P2P_MAX_NUM_INBOUND_PEERS=500
      - DIGD_P2P_MAX_NUM_OUTBOUND_PEERS=100
    expose:
      - port: 26656
        to:
          - global: true
      - port: 26657
        as: 80
        to:
          - global: true

profiles:
  compute:
    akash:
      resources:
        cpu:
          units: 1
        memory:
          size: 2Gi
        storage:
          size: 32Gi
  placement:
    dcloud:
      attributes:
        host: akash
      pricing:
        akash:
          denom: uakt
          amount: 1000

deployment:
  akash:
    dcloud:
      profile: akash
      count: 1
