# This is a basic workflow that is manually triggered

name: dig

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push, pull_request]

# This workflow makes x86_64 binaries for mac, windows, and linux.

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
        targetos: [darwin, linux]
    name: dig ${{ matrix.arch }} for ${{ matrix.targetos }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
        env:
          GOOS: ${{ matrix.targetos }}
          GOARCH: ${{ matrix.arch }}

      - name: Compile dig
        run: |
          go mod download
          cd cmd/digd
          go build .
          go install .

      - name: Compile airdrop
        run: |
          cd airdrop
          go mod download
          go build .
          go install .
          
      - name: Check Genesis transactions
        run: |
          digd init test
          cp -r networks/testnet-2/* ~/.dig/config
          digd collect-gentxs
          cp ~/.dig/config/genesis.json cmd/digd
          
          
# now uploads genesis.json and bin
      - uses: actions/upload-artifact@v2
        with:
          name: digd ${{ matrix.targetos }} ${{ matrix.arch }}
          path: cmd/digd
