# This is a basic workflow that is manually triggered

name: Validate genesis

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push, pull_request, workflow_dispatch]

# This workflow makes x86_64 binaries for mac, windows, and linux.

jobs:
  genesis:
    runs-on: ubuntu-latest
    name: validate genesis
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2.1.3
        with: 
          go-version: '^1.16.7'

      - name: Compile dig
        run: |
          go mod download
          cd cmd/digd
          go build .
          go install .
          
      - name: Check Genesis transactions
        run: |
          digd init test
          cp networks/testnet-2/genesis.json ~/.dig/config
          cp -r networks/testnet-2/gentx ~/.dig/config
          digd collect-gentxs
          cp ~/.dig/config/genesis.json cmd/digd
          digd validate-genesis
          
          
# now uploads genesis.json and bin
      - uses: actions/upload-artifact@v2
        with:
          path: .dig/config/genesis.json
