# This is a basic workflow that is manually triggered

name: compile dig

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push, pull_request, workflow_dispatch]

# This workflow makes x86_64 binaries for mac, windows, and linux.

jobs:
  starport:
    runs-on: ubuntu-latest
    steps:
      - name: kick tires
        run: |
          curl https://get.starport.network/starport! | bash
          starport serve



        
          
          

